version: "3.0"
services: 
    mysql:
        image: mysql
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=apps-db
        volumes: 
            - ./apps-db-data:/var/lib/mysql